---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1601535/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp hubungi.html $DEPLOYPATH
    - /bin/cp layanan.html $DEPLOYPATH
    - /bin/cp tentang.html $DEPLOYPATH
    - /bin/cp style.css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH